# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f43f0484a715b5881419c7754c9f7518b2ccd8817d71118634a53431e3e580b32a96bce8ed7eba7b3e14ad000c633b178742e48d78a8295a00e7fc22f8b9758c

test:
  secret_key_base: 5280ce53e7e8b1f15d7d40699b9f69a1d9b2809f801b98f9eced4a341640563918c5e61219af79c8431e957b01816f77c28aed65b0c83f72891518797f365ed3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
